# Generated by Django 2.0.5 on 2019-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewData',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=200)),
                ('review_ratings', models.IntegerField()),
                ('review_content', models.TextField(max_length=1000)),
            ],
        ),
    ]
